command:
  - "gunicorn"
  - "main:app"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"

env:
  - name: "DATABRICKS_HOST"
    value: "adb-1108746899088703.3.azuredatabricks.net"
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "6880e1544b69181f"   